export type AppMode = 'generate' | 'edit' | 'thumbnail' | 'merge';
export type ActiveTab = 'result' | 'gallery';

export interface AspectRatio {
  id: '1:1' | '3:4' | '4:3' | '9:16' | '16:9';
  label: string;
  description: string;
}

export interface GalleryImage {
    id?: number; // Optional as it's auto-generated by IndexedDB
    imageData: string;
}